### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by annefou** [deepthi1107/Outreachy_contribution_Galaxy_Community.github.io#1]
Awesome website! Well done!

Some specific comments to your [Analysis](https://deepthi1107.github.io/Outreachy_contribution_Galaxy_Community.github.io/page5.html):

- Opening time for schools: conclusions cannot be based on a single day meteorological condition, especially in the past, however if a heat wave is forecasted in the coming days then obviously this could be taken into account

- Working in the fields: This is very true and a general situation: more and more working hours will have to be somehow adapted to local conditions wherever that is possible.

- Visiting hours: this also is common sense, although there will be implications for the related activities (transports, tourist attractions, food and beverage businesses, etc.) and also it will require some practical organisation of occupations for the remaining time.

- Going out times: this makes sense and will also require societal adaptation, for instance to adapt the opening times for administrations, shops, transports, etc. It also means modifying working hours for such people working there.

- Circulation of electric vehicles: interesting! this is new to me and hence difficult to comment on. What is the issue? parking in the sun (which would require shaded parking lots) or malfunctions (issue with electric wires) or really usage in the sun?

- Air conditioning in buses: This is very interesting too. I guess that installing AC in all buses involves more fundamental changes and expenses than what could be saved by not turning AC on during the "coldest hours".

- Pasturing: This is typically an example where changing "active times" affects "things" outside human being's control and it requires more thought to transform daytime animal behavior into nocturnal behavior (since it goes against their habits, instincts,  nycthemeral cycles, etc.). Note that this sort of issue also concerns insects and plants. a difficult question indeed.

General comment:
Sometimes, conlusions are infered based on a single day of data which is not really possible. Here we need to keep in mind the difference between "weather" (meteorological conditions at a specific time and place) and "climate" (longer term trends, generally over a wide surface area).
We cannot make long-term decisions/suggestions based on weather only and we would need to make a climate analysis (this was of course not the purpose of the question here!).

Another think that can be interesting to think about is what can be done to "reverse" the situation or at least improve it, for instance create bicycle lanes separated from motor vehicles, planting trees to create shade and retain moisture, switch to crops which better resist dry conditions, produce food for local consumption rather than export, build with techniques facilitating passive ventilation, harvest solar energy for cooking but also to produce electricity and pre-heat water (which can then be brought to boil with less energy, or used in a desalination process), use phase-changing material to store/transport/release heat, use LEDs  for lighting instead of energy-hungry alternatives, etc.

Some of these ideas are probably already implemented in India, although we do not know much about these elsewhere, and it is very likely that there are good solutions, possibly inspired from practices in different contexts/countries (see how working time and opening hours for shops and bars/restaurants are adapted in Spain and north Africa)

A lot of small/individual actions to save fossil fuel and water or  reduce emissions can add-up and have large impacts, a lot could be achieved by informing/educating people.

Thanks!

**Comment by deepthi1107** [comment]
Thanks for the feedback. I will make changes and reach out to you @annefou

**Comment by deepthi1107** [comment]
Thanks for your appreciation for the website.

-> Opening time for schools: In the analysis page, I have given a webpage reference that gives an explanation about heatwaves forecasted and also predicts the future. Hence, I have given a conclusion based on the forecasted analysis on that webpage.
The forecasted data can be seen at "Click here to know more about studies on heatwaves"
->Working in the fields: I have added a few more information.
->visiting hours: content is updated.
->Cirulation of electric vehicles: content is updated.
->Air conditioning in buses: Taking the real-life examples into consideration, in India only a few busses have ac because few people travel in that and also installation of ac in all the busses would be costlier. Hence, I suggest that running ac busses only for a few hours rather than the whole day would be a better idea.
->Pasturing: Here, I am speaking about the animals which people raise in their homes. In India, villagers raise animals to full fill their daily purposes. Hence, the proposed idea would work fine.

Images are added for reference.
Solutions to the problems would be mentioned sooner. @annefou 

Feedback on the changes would help me to make a richer website.

**Comment by deepthi1107** [comment]
Yes, I agree that conclusions based on single-day temperature are very difficult and also nearly impossible. Hence, I have given generalized problems faced in India due to heatwaves.

**Comment by deepthi1107** [comment]
@annefou, I have also added some tips to take to protect from heatwaves.

I have updated the page. Please do give a review/feedback.

**Comment by j34ni** [comment]
> Following are a few analyses made using air temperature on the day 2022-03-31 from 00:00:00 to 16:00:00

Since we only have data for **a single day** we have to be very careful about what can be concluded based on this information only.

Any hypothesis has to be supported by appropriate analysis with data covering a relevant (long) period of time and the entire geographical region of interest, for instance to calculate **trends**. 

You can also cite external work results, making sure that you reference it explicitly in the text.

Check all the pictures, illustrations, photos, graphs, images that you have not created yourselves, make sure that they have a **license** and add the source.

**Comment by deepthi1107** [comment]
Thanks for the feedback, surely work on the feedback and get back to you @j34ni

**Comment by deepthi1107** [comment]
@annefou @j34ni, I have updated the webpage with suitable articles/blogs. Could you check and give feedback.

**Comment by deepthi1107** [comment]
@annefou, Are there any updations yet to be done from my side?

**Comment by annefou** [comment]
It looks good to me.

**Comment by deepthi1107** [comment]
Thanks @annefou for the feedback.

**Comment by deepthi1107** [comment]
@annefou, Can you please close the issue.

**Comment by deepthi1107** [comment]
Thanks @annefou, @j34ni for the guidance.
